"""
Plot steady-state mutual linearity figures from saved NPZ data.

This file reads the data files generated by simulation.py.  It keeps the same
plotting style as the original combined script for local_width = 0.05 and 0.5.
For local_width = 1.0, it additionally connects the data points to show the
nonlinear curve and suppresses the R^2 / chi annotation.

Expected input files:
    data/0.05_mutual_linearity.npz
    data/0.5_mutual_linearity.npz
    data/1.0_mutual_linearity.npz

Usage:
    python plot.py
    python plot.py --widths 0.05 0.5 1.0
"""

import argparse
import os
import math
import numpy as np
import matplotlib.pyplot as plt


SINGLE_COLUMN_WIDTH_IN = 1.95
FIG_HEIGHT_IN = 1.55

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__)) if "__file__" in globals() else os.getcwd()
FIGURES_DIR = os.path.join(SCRIPT_DIR, "figures")
DATA_DIR = os.path.join(SCRIPT_DIR, "data")

OBS_KEYS = (
    "occ_A",
    "occ_B",
    "occ_C",
    "rho_A",
    "rho_B",
    "power_B",
    "omega",
    "total_power",
    "sigma_B",
)
DEFAULT_OBS_INDEX = {key: i for i, key in enumerate(OBS_KEYS)}

# Colorblind-safe, publication-friendly palette for observable-vs-lambda plots.
OBSERVABLE_STYLES = (
    ("occ_A", r"$\tau_{A, \rm ss}$", "o", "-", "blue"),
    ("occ_B", r"$\tau_{B, \rm ss}$", "s", "--", "orange"),
    ("occ_C", r"$\tau_{C, \rm ss}$", "^", ":", "#B2182B"),
)

# The uploaded local_width = 1.0 data contains one anomalous point at
# lambda = -150.  Remove it from all plots for that width.
OUTLIER_LAMBDAS_BY_WIDTH = {
    1.0: (-150.0,),
}


def width_to_prefix(width):
    return f"{width}_"


def set_style():
    plt.rcParams.update({
        "font.family": "serif",
        "mathtext.fontset": "cm",
        "font.size": 9.0,
        "axes.labelsize": 9.0,
        "axes.titlesize": 9.0,
        "xtick.labelsize": 8.2,
        "ytick.labelsize": 8.2,
        "legend.fontsize": 7.6,
        "axes.linewidth": 0.8,
        "xtick.direction": "in",
        "ytick.direction": "in",
        "xtick.top": True,
        "ytick.right": True,
        "xtick.major.width": 0.8,
        "ytick.major.width": 0.8,
        "xtick.minor.width": 0.6,
        "ytick.minor.width": 0.6,
        "legend.frameon": False,
        "savefig.bbox": "tight",
        "savefig.pad_inches": 0.01,
    })


def load_results_npz(filename):
    data = np.load(filename, allow_pickle=True)
    obs_keys = [str(k) for k in data["obs_keys"]]
    return dict(
        lambdas=data["lambdas"],
        values=data["values"],
        errors=data["errors"],
        obs_keys=np.array(obs_keys),
        obs_index={key: i for i, key in enumerate(obs_keys)},
    )


def get_obs(results, key):
    idx = results.get("obs_index", DEFAULT_OBS_INDEX)[key]
    return results["values"][:, idx], results["errors"][:, idx]


def finite_mask(*arrays):
    """Return a mask that is True only where all provided arrays are finite."""
    mask = None
    for arr in arrays:
        if arr is None:
            continue
        arr = np.asarray(arr)
        current = np.isfinite(arr)
        mask = current if mask is None else (mask & current)
    if mask is None:
        raise ValueError("finite_mask requires at least one non-None array.")
    return mask


def filter_finite_xy(x, y, xerr=None, yerr=None, lambdas=None):
    """Remove NaN/inf points from mutual-linearity data and associated errors."""
    mask = finite_mask(x, y, xerr, yerr, lambdas)
    x_f = np.asarray(x)[mask]
    y_f = np.asarray(y)[mask]
    xerr_f = None if xerr is None else np.asarray(xerr)[mask]
    yerr_f = None if yerr is None else np.asarray(yerr)[mask]
    lambdas_f = None if lambdas is None else np.asarray(lambdas)[mask]
    return x_f, y_f, xerr_f, yerr_f, lambdas_f


def outlier_mask_for_width(lambdas, width):
    """Return a row mask that removes manually identified anomalous lambda points."""
    lambdas = np.asarray(lambdas, dtype=np.float64)
    mask = np.ones(lambdas.shape, dtype=bool)
    for bad_lam in OUTLIER_LAMBDAS_BY_WIDTH.get(float(width), ()):  # exact width keys
        mask &= ~np.isclose(lambdas, bad_lam, rtol=0.0, atol=1.0e-10)
    return mask


def remove_outlier_rows(results, width):
    """Remove anomalous lambda rows from values/errors before plotting."""
    mask = outlier_mask_for_width(results["lambdas"], width)
    if np.all(mask):
        return results

    removed = results["lambdas"][~mask]
    return dict(
        lambdas=results["lambdas"][mask],
        values=results["values"][mask],
        errors=results["errors"][mask],
        obs_keys=results["obs_keys"],
        obs_index=results["obs_index"],
    )


def fit_line(x, y, xerr=None, yerr=None):
    """
    Symmetric line fit using Deming regression.
    If xerr/yerr are not provided, fall back to lambda_ratio = 1
    (orthogonal regression / total least squares).
    """
    x = np.asarray(x, dtype=np.float64)
    y = np.asarray(y, dtype=np.float64)

    xbar = np.mean(x)
    ybar = np.mean(y)

    dx = x - xbar
    dy = y - ybar

    Sxx = np.mean(dx * dx)
    Syy = np.mean(dy * dy)
    Sxy = np.mean(dx * dy)

    if xerr is None or yerr is None:
        lambda_ratio = 1.0
    else:
        sx2 = np.mean(np.asarray(xerr, dtype=np.float64) ** 2)
        sy2 = np.mean(np.asarray(yerr, dtype=np.float64) ** 2)
        lambda_ratio = sy2 / sx2 if sx2 > 0 else 1.0

    if abs(Sxy) < 1.0e-15:
        slope = np.nan
        intercept = np.nan
    else:
        disc = (Syy - lambda_ratio * Sxx) ** 2 + 4.0 * lambda_ratio * Sxy ** 2
        slope = (Syy - lambda_ratio * Sxx + np.sqrt(disc)) / (2.0 * Sxy)
        intercept = ybar - slope * xbar

    r = np.corrcoef(x, y)[0, 1]
    r2 = r * r

    cov = np.full((2, 2), np.nan)
    return slope, intercept, cov, r2


def save_figure_both(fig, filebase):
    """Save the same figure as both PDF and SVG."""
    fig.savefig(filebase + ".pdf")
    fig.savefig(filebase + ".svg")


def plot_mutual_linearity(
    results,
    xkey,
    ykey,
    xlabel,
    ylabel,
    filebase,
    panel_label=None,
    annotate=True,
    fit=True,
    connect_points=False,
):
    set_style()
    x_raw, xerr_raw = get_obs(results, xkey)
    y_raw, yerr_raw = get_obs(results, ykey)
    x, y, xerr, yerr, lambdas = filter_finite_xy(
        x_raw, y_raw, xerr_raw, yerr_raw, results["lambdas"]
    )

    if x.size == 0:
        raise ValueError(f"No finite data points remain for {ykey} vs {xkey}.")

    if fit and x.size >= 2:
        slope, intercept, cov, r2 = fit_line(x, y, xerr, yerr)
    else:
        slope, intercept, r2 = np.nan, np.nan, np.nan

    fig, ax = plt.subplots(
        1, 1,
        figsize=(SINGLE_COLUMN_WIDTH_IN, FIG_HEIGHT_IN),
        constrained_layout=True,
    )

    if connect_points:
        order = np.argsort(lambdas)
        ax.plot(
            x[order],
            y[order],
            ls="--",
            lw=1.0,
            color="0.35",
            zorder=1,
        )

    ax.errorbar(
        x,
        y,
        xerr=xerr,
        yerr=yerr,
        fmt="o",
        color="black",
        ecolor="0.55",
        elinewidth=0.75,
        capsize=2.0,
        markersize=3,
        markerfacecolor="white",
        markeredgecolor="black",
        markeredgewidth=0.85,
        zorder=3,
    )

    if fit and np.isfinite(slope) and np.isfinite(intercept):
        xs = np.linspace(np.min(x), np.max(x), 200)
        ax.plot(xs, slope * xs + intercept, color="#B2182B", lw=1.25, zorder=2)

    ax.set_xlabel(xlabel)
    ax.set_ylabel(ylabel)
    ax.tick_params(direction="in", top=True, right=True)

    if panel_label is not None:
        ax.text(0.03, 0.96, panel_label, transform=ax.transAxes, va="top", ha="left")
    if annotate and fit and np.isfinite(r2) and np.isfinite(slope):
        text = rf"$R^2={r2:.4f}$" + "\n" + rf"$\chi={slope:.4g}$"
        ax.text(0.97, 0.06, text, transform=ax.transAxes, va="bottom", ha="right")

    save_figure_both(fig, filebase)
    plt.close(fig)
    return slope, intercept, r2


def plot_observables_vs_lambda(results, filebase):
    set_style()
    lambdas = results["lambdas"]
    fig, ax = plt.subplots(
        1, 1,
        figsize=(SINGLE_COLUMN_WIDTH_IN, FIG_HEIGHT_IN),
        constrained_layout=True,
    )

    for key, label, marker, linestyle, color in OBSERVABLE_STYLES:
        y_raw, yerr_raw = get_obs(results, key)
        mask = finite_mask(lambdas, y_raw, yerr_raw)
        lambdas_f = lambdas[mask]
        y = y_raw[mask]
        yerr = yerr_raw[mask]
        if y.size == 0:
            continue

        ax.errorbar(
            lambdas_f,
            y,
            xerr=None,
            yerr=yerr,
            fmt=marker,
            linestyle=linestyle,
            color=color,
            label=label,
            lw=1.05,
            ecolor=color,
            elinewidth=0.65,
            capsize=2.0,
            markersize=3.1,
            markerfacecolor="white",
            markeredgecolor=color,
            markeredgewidth=0.85,
            zorder=3,
        )

    ax.set_xlabel(r"torque strength $\lambda$")
    ax.set_ylabel(r"fraction")
    ax.tick_params(direction="in", top=True, right=True)
    ax.legend(frameon=False, handlelength=1.5)
    save_figure_both(fig, filebase)
    plt.close(fig)


def make_all_figures(results, width, outdir="figures"):
    os.makedirs(outdir, exist_ok=True)
    results = remove_outlier_rows(results, width)
    file_suffix = width_to_prefix(width)

    # For width = 1.0, emphasize nonlinear behavior by connecting points and
    # suppressing line-fit annotations.  For 0.05 and 0.5, keep the original style.
    nonlinear_case = math.isclose(float(width), 1.0, rel_tol=0.0, abs_tol=1.0e-12)
    fit = not nonlinear_case
    annotate = not nonlinear_case
    connect_points = nonlinear_case

    stats = {}
    stats["occA_occB"] = plot_mutual_linearity(
        results,
        "occ_B",
        "occ_A",
        r"$\tau_{B, \rm ss}$",
        r"$\tau_{A, \rm ss}$",
        os.path.join(outdir, file_suffix + "occA_vs_occB"),
        panel_label=None,
        annotate=annotate,
        fit=fit,
        connect_points=connect_points,
    )
    stats["rhoA_rhoB"] = plot_mutual_linearity(
        results,
        "rho_B",
        "rho_A",
        r"$\pi(\theta_B)$",
        r"$\pi(\theta_A)$",
        os.path.join(outdir, file_suffix + "rhoA_vs_rhoB"),
        panel_label=None,
        annotate=annotate,
        fit=fit,
        connect_points=connect_points,
    )
    stats["powerB_occC"] = plot_mutual_linearity(
        results,
        "occ_C",
        "power_B",
        r"$\tau_{C, \rm ss}$",
        r"$P^{\rm in}_B$",
        os.path.join(outdir, file_suffix + "powerB_vs_occC"),
        panel_label=None,
        annotate=annotate,
        fit=fit,
        connect_points=connect_points,
    )
    stats["sigmaB_occC"] = plot_mutual_linearity(
        results,
        "occ_C",
        "sigma_B",
        r"$\tau_{C, \rm ss}$",
        r"$\sigma_B$",
        os.path.join(outdir, file_suffix + "sigmaB_vs_occC"),
        panel_label=None,
        annotate=annotate,
        fit=fit,
        connect_points=connect_points,
    )
    plot_observables_vs_lambda(results, os.path.join(outdir, file_suffix + "observables_vs_lambda"))

    return stats


def parse_args():
    parser = argparse.ArgumentParser(description="Plot saved mutual linearity data.")
    parser.add_argument("--widths", type=float, nargs="+", default=[0.05, 0.5, 1.0],
                        help="List of local_width values to plot.")
    parser.add_argument("--allow_missing", action="store_true",
                        help="Skip missing data files instead of raising an error.")
    return parser.parse_args()


def main():
    args = parse_args()
    os.makedirs(FIGURES_DIR, exist_ok=True)

    all_stats = {}
    for width in args.widths:
        file_suffix = width_to_prefix(width)
        filename = os.path.join(DATA_DIR, file_suffix + "mutual_linearity.npz")

        if not os.path.isfile(filename):
            msg = f"Missing data file: {filename}"
            if args.allow_missing:
                print(msg + "  Skip.")
                continue
            raise FileNotFoundError(msg)

        print(f"Load data from: {filename}")
        results = load_results_npz(filename)
        stats = make_all_figures(results, width, outdir=FIGURES_DIR)
        all_stats[file_suffix.rstrip("_")] = stats

    print(all_stats)


if __name__ == "__main__":
    main()
